/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-01-06 13:13:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;

public final class phishing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--A Design by W3layouts\r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Phishing Site</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tbackground:url(./images/bg.jpg) ;\r\n");
      out.write("}\t\r\n");
      out.write(".wrap{\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\twidth:1000px;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\t\r\n");
      out.write(".title h1{\r\n");
      out.write("\tfont-size:60px;\r\n");
      out.write("\tcolor:RED;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin-top:100px;\r\n");
      out.write("\ttext-shadow:6px 1px 6px #333;\r\n");
      out.write("\tfont-family: 'Fjalla One', sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".title h2{\r\n");
      out.write("\tfont-size:40px;\r\n");
      out.write("\tcolor:RED;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin-bottom:1px;\r\n");
      out.write("\ttext-shadow:6px 1px 6px #333;\r\n");
      out.write("\tfont-family: 'Fjalla One', sans-serif;\r\n");
      out.write("\tmargin-top: -20px;\r\n");
      out.write("}\t\t\r\n");
      out.write(".logo p{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\tmargin-top:1px;\r\n");
      out.write("\tfont-family: 'Fjalla One', sans-serif;\r\n");
      out.write("}\t\r\n");
      out.write(".gray {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tbackground: rgba(12, 52, 77, 0.34);\r\n");
      out.write("\ttext-shadow: 0 -1px 1px rgba(0, 0, 0, 0.25);\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\t-webkit-border-radius: 4px;\r\n");
      out.write("\t-moz-border-radius: 4px;\r\n");
      out.write("\t-o-border-radius: 4px;\r\n");
      out.write("\tcolor:yellow;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\tpadding:30px 30px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tfont-family: 'Fjalla One', sans-serif;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\t\r\n");
      out.write(".ag-3d_button.orange {\r\n");
      out.write("\tbox-shadow: rgba(155, 142, 50, 0.98) 0 3px 0px, rgba(0, 0, 0, 0.3) 0 3px 3px;\r\n");
      out.write("}\r\n");
      out.write(".ag-3d_button {\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: 10px 25px 12px;\r\n");
      out.write("}\r\n");
      out.write(".orange {\r\n");
      out.write("\tbackground: #fdde02;\r\n");
      out.write("\tbackground: -moz-linear-gradient(top,  #fdde02 0%, #dec829 99%);\r\n");
      out.write("\tbackground: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdde02), color-stop(99%,#dec829));\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top,  #fdde02 0%,#dec829 99%);\r\n");
      out.write("\tbackground: -o-linear-gradient(top,  #fdde02 0%,#dec829 99%);\r\n");
      out.write("\tbackground: -ms-linear-gradient(top,  #fdde02 0%,#dec829 99%);\r\n");
      out.write("\tbackground: linear-gradient(to bottom,  #fdde02 0%,#dec829 99%);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fdde02', endColorstr='#dec829',GradientType=0 );\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\ttext-shadow:1px 1px 3px rgba(155, 142, 50, 0.98);\r\n");
      out.write("\tborder: 1px solid rgba(155, 142, 50, 0.98);\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".orange:hover {\r\n");
      out.write("\tbackground: #dec829;\r\n");
      out.write("\tbackground: -moz-linear-gradient(top,  #dec829 1%, #fdde02 100%);\r\n");
      out.write("\tbackground: -webkit-gradient(linear, left top, left bottom, color-stop(1%,#dec829), color-stop(100%,#fdde02));\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top,  #dec829 1%,#fdde02 100%);\r\n");
      out.write("\tbackground: -o-linear-gradient(top,  #dec829 1%,#fdde02 100%);\r\n");
      out.write("\tbackground: -ms-linear-gradient(top,  #dec829 1%,#fdde02 100%);\r\n");
      out.write("\tbackground: linear-gradient(to bottom,  #dec829 1%,#fdde02 100%);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#dec829', endColorstr='#fdde02',GradientType=0 );\r\n");
      out.write("}\r\n");
      out.write(".footer{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tright:10px;\r\n");
      out.write("\tbottom:10px;\r\n");
      out.write("}\t\r\n");
      out.write(".footer a{\r\n");
      out.write("\tcolor:yellow;\r\n");
      out.write("}\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: black;\">\r\n");

String url=URLDecoder.decode(request.getParameter("url"));

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t   <div class=\"logo\">\r\n");
      out.write("\t   \t\t<p>Phishing Site</p>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   <div class=\"title\" style=\"text-align: left;color: yellow\">\r\n");
      out.write("\t  \t\t <h1>Site that you are trying to access is a phishing site. </h1>\r\n");
      out.write("\t   \t\t <h2>Possible Reasons:<BR>\r\n");
      out.write("\t   \t\t Site URL may be diffrent.<BR>\r\n");
      out.write("\t   \t\t Site host name may be diffrent.<BR>\r\n");
      out.write("\t   \t\t Site may contain a malware or may be a phishing site.<BR>\r\n");
      out.write("\t   \t\t\r\n");
      out.write("\t   \t\t </h2>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>   \r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t    <div class=\"gray\">\r\n");
      out.write("  \t    \t<a href=\"");
      out.print(url);
      out.write("\" class=\"ag-3d_button orange\">Continue Access </a><a href=\"javascript:window.close();\" class=\"ag-3d_button orange\">Close  </a>\r\n");
      out.write("  \t     </div>\r\n");
      out.write("   </div>  \r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t Design by-<a href=\"http://w3layouts.com\">W3Layouts</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
